### PR TITLE
Added link to FLASHQuant installer files

### PR DESCRIPTION
**Pull request by JeeH-K**
#### Brief description of what is fixed or changed

Added a link to FLASHQuant installer files and fixed a few errors on the webpage

### CODE REVIEW

**Comment by JeeH-K** [comment]
Not sure what I did to make the netfiy fail..

**Comment by jpfeuffer** [comment]
It happens from time to time. Would be cool to fix. Has something to do with netlifys caching behavior.

**Comment by JeeH-K** [comment]
@jpfeuffer pheww, thanks for letting me know! Is there any way to know if we are safe to merge or not then?

**Comment by jpfeuffer** [comment]
No, you have to manually restart Netlify without cache

**Comment by jpfeuffer** [comment]
Looks like it. Did you sign up already?
If so, me, Timo or Tjeerd would probably need the email you used for signup.

**Comment by JeeH-K** [comment]
yes same ID: jihyung.kim@uni-tuebingen.de

**Comment by jpfeuffer** [comment]
Ok tried to add you

**Comment by JeeH-K** [comment]
> ### ✅ Deploy Preview for _openms_ ready!
> Name	Link
> 🔨 Latest commit	
> 🔍 Latest deploy log	https://app.netlify.com/sites/openms/deploys/6577619018523f388c9053f9
> 😎 Deploy Preview	https://deploy-preview-123--openms.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/openms/configuration/deploys#deploy-notifications)._

@jpfeuffer thanks a mil! It succeeded! Don't know why it is still showing the deploy as failed here tho

**Review by matteopilz — APPROVED** [review]
I don't know why the netlify build is not working on GitHub, but the changes look good.

**Comment by JeeH-K** [comment]
> I don't know why the netlify build is not working on GitHub, but the changes look good.

Ah, so the deploy preview from Netlify worked above. It's just the success from the rerun is somehow not linked to this PR page.

**Pull request merged**
