### PR TITLE
Fix Quick Facts for Users

### PR DESCRIPTION
**Pull request by matteopilz**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Would be cool to automate, see the also open #115

**Comment by jpfeuffer** [comment]
Why is OpenMS badge gone? Can we integrate this together with the other PR?

**Comment by matteopilz** [comment]
The banner is now back. If everything works, I would say we merge this PR, as there is some additional stuff to the banners. Afterwards, I can take a look at the other one.

**Review by enetz — APPROVED** [review]
Looks like this has been forgotten for a while.
@matteopilz can you fix the merge conflict, that has popped up here and merge this?

**Pull request merged**
