### PR TITLE
update pyopenms logo

### PR DESCRIPTION
**Pull request by timosachsenberg**
probably needs update of pyopenms css in scientific hugo theme as it is streched

### CODE REVIEW

**Comment by timosachsenberg** [comment]
@rahul799 or @jpfeuffer how to quickly fix this?
logo is strangely stretched
image

**Comment by jpfeuffer** [comment]
.. the css is in the theme?? why??

**Review by jpfeuffer — CHANGES_REQUESTED** [review]
Please delete old logos. All logos should be under the folder logos. Our custom CSS should be in our repo, not in the base theme.

**Comment by jpfeuffer** [comment]
Even if there was a reason, it will be hard to convince me that it is really necessary.

Every theme file can be easily overwritten from outside the theme.

**Comment by matteopilz** [comment]
I think I'm lacking permission to update to the PR branch.

**Pull request closed without merging**
